# Generated by Django 4.0.1 on 2022-04-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=2500),
        ),
    ]
